sudo: required
services:
  - docker

before_install:
  - docker build -t simonnewell/docker-react -f Dockerfile.dev .

script:
  # Course doc mentions the change needed from original course material.
  # if get rakefile not found. Put: language: generic at the top of this file.
  #- docker run simonnewell/docker-react npm run test -- --coverage
  - docker run -e CI=true simonnewell/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: elasticbeanstalk-eu-west-2-108919574332
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
